In [1]:
!pip install numpy

Requirement already satisfied: numpy in C:\Users\TECH-GENIUSES\Desktop\AI ML\venv\Lib\site-packages (2.4.6)

In [2]:
print("ok")
import numpy as np
num = [1,2,3,4,5]
new = np.array(num)
print(new)

ok
[1 2 3 4 5]

In [4]:
print(num*6)
print(new*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]

In [5]:
import pandas as pd
print(pd.__version__)

3.0.3

In [6]:
read = pd.read_csv("employee.csv")
print(read)

   EmployeeID    Name Department Region  Salary  Bonus  Experience
0         101    John         IT   East  5000.0  500.0         3.0
1         102    Sara         HR   West  4500.0  450.0         5.0
2         103    Mike         IT   East  6000.0  600.0         7.0
3         104    Emma         HR  North  4000.0    NaN         2.0
4         105   David    Finance  South  5500.0  550.0         4.0
5         106    Lisa         IT   West     NaN  700.0         6.0
6         107     Tom    Finance  South  7000.0  700.0        10.0
7         108    Anna         HR   East  4800.0    NaN         3.0
8         109   Chris         IT  North  6200.0  620.0         8.0
9         110  Sophia    Finance   West  5300.0  530.0         NaN

In [7]:
read.head()

   EmployeeID   Name Department Region  Salary  Bonus  Experience
0         101   John         IT   East  5000.0  500.0         3.0
1         102   Sara         HR   West  4500.0  450.0         5.0
2         103   Mike         IT   East  6000.0  600.0         7.0
3         104   Emma         HR  North  4000.0    NaN         2.0
4         105  David    Finance  South  5500.0  550.0         4.0

In [9]:
read.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  10 non-null     int64
 1   Name        10 non-null     str
 2   Department  10 non-null     str
 3   Region      10 non-null     str
 4   Salary      9 non-null      float64
 5   Bonus       8 non-null      float64
 6   Experience  9 non-null      float64
dtypes: float64(3), int64(1), str(3)
memory usage: 692.0 bytes

In [10]:
read.describe()

       EmployeeID       Salary       Bonus  Experience
count    10.00000     9.000000    8.000000    9.000000
mean    105.50000  5366.666667  581.250000    5.333333
std       3.02765   926.012959   90.622845    2.645751
min     101.00000  4000.000000  450.000000    2.000000
25%     103.25000  4800.000000  522.500000    3.000000
50%     105.50000  5300.000000  575.000000    5.000000
75%     107.75000  6000.000000  640.000000    7.000000
max     110.00000  7000.000000  700.000000   10.000000

In [13]:
print(read.isnull())
read.isnull().sum()

   EmployeeID   Name  Department  Region  Salary  Bonus  Experience
0       False  False       False   False   False  False       False
1       False  False       False   False   False  False       False
2       False  False       False   False   False  False       False
3       False  False       False   False   False   True       False
4       False  False       False   False   False  False       False
5       False  False       False   False    True  False       False
6       False  False       False   False   False  False       False
7       False  False       False   False   False   True       False
8       False  False       False   False   False  False       False
9       False  False       False   False   False  False        True

EmployeeID    0
Name          0
Department    0
Region        0
Salary        1
Bonus         2
Experience    1
dtype: int64

In [14]:
read["Salary"] = read["Salary"].fillna(1)
read["Bonus"] = read["Bonus"].fillna(0)

In [16]:
print(read["Salary"])
print(read["Bonus"])

0    5000.0
1    4500.0
2    6000.0
3    4000.0
4    5500.0
5       1.0
6    7000.0
7    4800.0
8    6200.0
9    5300.0
Name: Salary, dtype: float64
0    500.0
1    450.0
2    600.0
3      0.0
4    550.0
5    700.0
6    700.0
7      0.0
8    620.0
9    530.0
Name: Bonus, dtype: float64

In [17]:
read["Newcoloumn"] = 'New place'
print(read)

   EmployeeID    Name Department Region  Salary  Bonus  Experience Newcoloumn
0         101    John         IT   East  5000.0  500.0         3.0  New place
1         102    Sara         HR   West  4500.0  450.0         5.0  New place
2         103    Mike         IT   East  6000.0  600.0         7.0  New place
3         104    Emma         HR  North  4000.0    0.0         2.0  New place
4         105   David    Finance  South  5500.0  550.0         4.0  New place
5         106    Lisa         IT   West     1.0  700.0         6.0  New place
6         107     Tom    Finance  South  7000.0  700.0        10.0  New place
7         108    Anna         HR   East  4800.0    0.0         3.0  New place
8         109   Chris         IT  North  6200.0  620.0         8.0  New place
9         110  Sophia    Finance   West  5300.0  530.0         NaN  New place

In [20]:
read[read["Salary"]>5000]

   EmployeeID    Name Department Region  Salary  Bonus  Experience Newcoloumn
2         103    Mike         IT   East  6000.0  600.0         7.0  New place
4         105   David    Finance  South  5500.0  550.0         4.0  New place
6         107     Tom    Finance  South  7000.0  700.0        10.0  New place
8         109   Chris         IT  North  6200.0  620.0         8.0  New place
9         110  Sophia    Finance   West  5300.0  530.0         NaN  New place

In [26]:
read.groupby("Department")["Salary"].agg(["count","mean","sum","max"])

            count         mean      sum     max
Department
Finance         3  5933.333333  17800.0  7000.0
HR              3  4433.333333  13300.0  4800.0
IT              4  4300.250000  17201.0  6200.0